### ISSUE TITLE
Turn on/Off

### ISSUE THREAD

**Issue by JohnBergman** [thecogworks/Cogworks.SiteLock#2]
Can this be turned on / off without uninstalling/installing?  Also, if the Umbraco instance hosts multiple sites, does it affect a single one, or is it across the board?

**Comment by AnthonyCogworks** [comment]
Multiple sites will work just fine assuming you mean each site is a different domain.

Turning on and off is not something we considered, as it's kind of a set and forget lock-down. However, it should be really trivial to add a flag in the XML. I'll see if we can add it in the next couple days.

**Comment by JohnBergman** [comment]
So it's possible to lock one site, but not another in the same Umbraco instance?

Thanks for adding the setting :-)

**Comment by AnthonyCogworks** [comment]
YES! Simply specify the domains you want to lock in /config/SiteLock.config

`

<lockedDomains>

    <domain>localhost</domain>

    <domain>staging.sitelock.local</domain>

</lockedDomains>


`

Full doc:
https://our.umbraco.org/FileDownload?id=17537
