### ISSUE TITLE
This type of page is not served

### ISSUE THREAD

**Issue by bsubasic** [thecogworks/Cogworks.SiteLock#5]
Umbraco ver. 7.11.1
SiteLock ver. 1.2.0

I'm trying to figure out why this error appears, the main functionality is correct (website is locked and returns 403 forbidden if I'm not logged in) but it doesn't show up message from 403-sample.html template. I can access this page directly through the url btw. 

Is this some incompatibility with the newer Umbraco version or some misconfiguration in the IIS or web.config?

Thanks

![sitelock](https://user-images.githubusercontent.com/15268114/42813598-d5fe04b0-89c1-11e8-844b-adc46e60d273.jpg)

```<?xml version="1.0" encoding="utf-8"?>
<configuration>

  <lockedDomains>
    <!-- Uncomment to lock all domains -->
    <domain>*</domain>
  </lockedDomains>

  <allowedPaths>
    <!--Regular expressions-->
    <path>^/about(.*)</path>
    <path>/403-sample.html</path>
  </allowedPaths>

</configuration>```

**Comment by AnthonyCogworks** [comment]
I think you need a web.config setting:

https://www.troyhunt.com/solving-tyranny-of-http-403-responses/
